"""Add lat and lon

Revision ID: 02d29903ec58
Revises: f6a0508145bc
Create Date: 2021-07-09 04:30:29.326087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d29903ec58'
down_revision = 'f6a0508145bc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesh_node', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('mesh_node', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mesh_node', 'longitude')
    op.drop_column('mesh_node', 'latitude')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

