"""Rename sshhost to ssh_host

Revision ID: 92f5f1e7ad4c
Revises: d70b93682e1b
Create Date: 2021-06-16 23:46:30.835653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f5f1e7ad4c'
down_revision = 'd70b93682e1b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesh_group', sa.Column('ssh_host', sa.String(), nullable=True))
    op.drop_column('mesh_group', 'sshhost')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesh_group', sa.Column('sshhost', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mesh_group', 'ssh_host')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

