"""Change macaddr to uuid

Revision ID: f6a0508145bc
Revises: 1bdacce1e3c8
Create Date: 2021-07-04 21:25:17.326864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a0508145bc'
down_revision = '1bdacce1e3c8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mesh_node_macaddr_key', 'mesh_node', type_='unique')
    op.alter_column('mesh_node', 'macaddr', new_column_name='uuid')
    op.create_unique_constraint('mesh_node_uuid_key', 'mesh_node', ['uuid'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mesh_node_uuid_key', 'mesh_node', type_='unique')
    op.alter_column('mesh_node', 'uuid', new_column_name='macaddr')
    op.create_unique_constraint('mesh_node_macaddr_key', 'mesh_node', ['macaddr'])
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

